name: Lint Code

on: [workflow_dispatch, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4

    - name: Download & extract glualint
      run: |
        wget -c https://github.com/FPtje/GLuaFixer/releases/download/1.29.0/glualint-1.29.0-x86_64-linux.zip -O glualint.zip
        unzip -u glualint.zip
        rm glualint.zip
        echo "creating config for glualint"
        cat > glualint.json << ENDOFFILE
        {
          "lint_maxScopeDepth": 20,
          "lint_syntaxErrors": true,
          "lint_syntaxInconsistencies": true,
          "lint_deprecated": true,
          "lint_trailingWhitespace": true,
          "lint_whitespaceStyle": true,
          "lint_beginnerMistakes": true,
          "lint_emptyBlocks": true,
          "lint_shadowing": true,
          "lint_gotos": true,
          "lint_goto_identifier": true,
          "lint_doubleNegations": true,
          "lint_redundantIfStatements": true,
          "lint_redundantParentheses": true,
          "lint_duplicateTableKeys": true,
          "lint_profanity": true,
          "lint_unusedVars": true,
          "lint_unusedParameters": true,
          "lint_unusedLoopVars": true,
          "lint_inconsistentVariableStyle": false,
          "lint_spaceBetweenParens": false,
          "lint_spaceBetweenBrackets": false,
          "lint_spaceBetweenBraces": false,
          "lint_ignoreFiles": [],
          "lint_spaceBeforeComma": false,
          "lint_spaceAfterComma": false,
          "lint_maxLineLength": 150,
      
      
      
          "prettyprint_spaceBetweenParens": false,
          "prettyprint_spaceBetweenBrackets": false,
          "prettyprint_spaceBetweenBraces": false,
          "prettyprint_spaceEmptyParens": false,
          "prettyprint_spaceEmptyBraces": false,
          "prettyprint_spaceAfterLabel": false,
          "prettyprint_spaceBeforeComma": false,
          "prettyprint_spaceAfterComma": true,
          "prettyprint_semicolons": false,
          "prettyprint_cStyle": false,
          "prettyprint_removeRedundantParens": true,
          "prettyprint_minimizeParens": false,
          "prettyprint_assumeOperatorAssociativity": true,
          "prettyprint_indentation": "    ",
      
          "log_format": "github",
          "failOnWarning": true
        }
        ENDOFFILE
        echo "done"
        
    - name: Check code with glualint
      run: ./glualint --output-format github lint .
